steps:
  - name: "gcr.io/cloud-builders/gcloud"
    waitFor: ["-"]
    args:
      - functions
      - deploy
      - sherlock_gs_offers
      - --source=.
      - --region=europe-west1
      - --trigger-topic=sherlock_products
      - --runtime=python312
      - --max-instances=10
      - --timeout=300s

  - name: "gcr.io/cloud-builders/gcloud"
    waitFor: ["-"]
    args:
      - functions
      - deploy
      - sherlock_idealo
      - --source=.
      - --region=europe-west1
      - --trigger-topic=sherlock_products
      - --runtime=python312
      - --max-instances=10
      - --timeout=300s

  - name: "gcr.io/cloud-builders/gcloud"
    waitFor: ["-"]
    args:
      - functions
      - deploy
      - sherlock_pricerunner
      - --source=.
      - --region=europe-west1
      - --trigger-topic=sherlock_products
      - --runtime=python312
      - --max-instances=20
      - --timeout=300s

  # - name: "gcr.io/cloud-builders/gcloud"
  #   waitFor: ["-"]
  #   args:
  #     - functions
  #     - deploy
  #     - sherlock_kelkoo
  #     - --source=.
  #     - --region=europe-west1
  #     - --trigger-topic=sherlock_products
  #     - --runtime=python312
  #     - --max-instances=20
  #     - --timeout=300s

  # - name: "gcr.io/cloud-builders/gcloud"
  #   waitFor: ["-"]
  #   args:
  #     - functions
  #     - deploy
  #     - sherlock_kuantokusta
  #     - --source=.
  #     - --region=europe-west1
  #     - --trigger-topic=sherlock_products
  #     - --runtime=python312
  #     - --max-instances=10
  #     - --timeout=300s

  - name: "gcr.io/kaniko-project/executor:latest"
    waitFor: ["-"]
    args:
      - --destination=europe-docker.pkg.dev/panprices/panprices/google-shopping-searcher:latest
      - --dockerfile=./Dockerfile
      - --cache=true
      - --context=.
