steps:
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - functions
      - deploy
      - sherlock_idealo
      - --source=.
      - --region=europe-west3
      - --trigger-topic=sherlock_products
      - --runtime=python39
      - --max-instances=10
      - --timeout=300s
