steps:
  - name: "gcr.io/cloud-builders/gcloud"
    waitFor: ['-']
    args:
      - functions
      - deploy
      - sherlock_pricerunner
      - --source=.
      - --region=asia-east2
      - --trigger-topic=sherlock_products
      - --runtime=python39
      - --max-instances=20
      - --timeout=300s

  - name: "gcr.io/cloud-builders/gcloud"
    waitFor: ['-']
    args:
      - functions
      - deploy
      - sherlock_kelkoo
      - --source=.
      - --region=europe-west1
      - --trigger-topic=sherlock_products
      - --runtime=python39
      - --max-instances=20
      - --timeout=300s

  - name: "gcr.io/cloud-builders/gcloud"
    waitFor: ['-']
    args:
      - functions
      - deploy
      - sherlock_idealo
      - --source=.
      - --region=europe-west1
      - --trigger-topic=sherlock_products
      - --runtime=python39
      - --max-instances=10
      - --timeout=300s

  - name: "gcr.io/cloud-builders/gcloud"
    waitFor: ['-']
    args:
      - functions
      - deploy
      - sherlock_gs_offers
      - --source=.
      - --region=europe-west1
      - --trigger-topic=sherlock_products
      - --runtime=python39
      - --max-instances=10
      - --timeout=300s

  