steps:
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - functions
      - deploy
      - sherlock_idealo
      - --source=.
      - --region=europe-west3
      - --trigger-topic=sherlock_products
      - --runtime=python39
      - --max-instances=10
      - --timeout=300s

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - functions
      - deploy
      - sherlock_gs_offers
      - --source=.
      - --region=europe-west1
      - --trigger-topic=sherlock_products
      - --runtime=python39
      - --max-instances=10
      - --timeout=300s

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - functions
      - deploy
      - sherlock_kelkoo
      - --source=.
      - --region=europe-west1
      - --trigger-topic=sherlock_products
      - --runtime=python39
      - --max-instances=20
      - --timeout=300s
      # '--set-env-vars',
      #    'id_DE=96954745',
